# Generated by Django 3.2.7 on 2021-09-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20210926_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='none.png', upload_to='user/%y/%m'),
        ),
    ]
